# Generated by Django 3.2 on 2021-04-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('slug', models.CharField(max_length=50, verbose_name='Slug')),
                ('twitter_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ツイッターID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.channel')),
            ],
            options={
                'verbose_name': 'ライバー',
                'verbose_name_plural': 'ライバー',
            },
        ),
    ]
