# Generated by Django 3.2 on 2021-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijisanji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liver',
            name='ruby',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ルビ'),
        ),
    ]
