# Generated by Django 3.2 on 2021-04-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='チャンネル名')),
                ('cid', models.CharField(max_length=50, verbose_name='チャンネルID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'チャンネル',
                'verbose_name_plural': 'チャンネル',
            },
        ),
        migrations.CreateModel(
            name='Matome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'まとめ',
                'verbose_name_plural': 'まとめ',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50, verbose_name='動画ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True, verbose_name='サムネイル')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.channel')),
            ],
            options={
                'verbose_name': '動画',
                'verbose_name_plural': '動画',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=100, null=True, verbose_name='メモ')),
                ('start_at', models.IntegerField(default=0, null=True, verbose_name='開始時間')),
                ('end_at', models.IntegerField(default=0, null=True, verbose_name='終了時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('matome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.matome')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
            options={
                'verbose_name': 'シーン',
                'verbose_name_plural': 'シーン',
            },
        ),
    ]
