# Generated by Django 3.2 on 2021-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='temp', max_length=100, verbose_name='チャンネル名'),
            preserve_default=False,
        ),
    ]
